SoffanDD2480/assignment-1-DECIDE

- code/LIC_check.py
Implemented function for checking the LIC 2 request.
For doing that we use a function called "calculate_angle" witch calculate the angle given three points.
fixed #4
> Feat LIC 2 check implemented 

- code/LIC_check.py
The function checks if the LIC 3 is satisfied by the given set of points.
The function return True if the area of the triangle defined by the points is greater then the one given as parameter.
Fix #5
> Feat LIC 3 Check implemented 

- .gitignore
- code/decide.py
- code/test_decide.py
This PR implements the Decide class as part of the work for Issue #1.
Implemented Features:
- Core functionality of the Decide class.
Incomplete Work:
- Some parts of the implementation are not finalized.
- Unit tests are currently lacking for certain methods.
Linked Issue:
Closes #1  (when complete).
> Decide Class Implementation (Partial)

- code/decide.py
- code/test_decide.py
This PR completes the implementation of the Decide class for Issue #1, with the exception of the calculateCMV method.
Completed Work:
- All required LICs (Logical Implementation Conditions) have been implemented.
- Supporting methods and functionality are in place.
Remaining Work:
- calculateCMV depends on all LICs being fully implemented and tested.
Linked Issue:
Closes #1
> Complete Implementation of Decide Class (Partial, Except CMV)

- code/LIC_check.py
The function checks if the LIC 4 is satisfied by the given set of points.
The function return True if there exists at least one set of q_pts consecutive data point that lie in more than quads quadrants.
fix #6
> feat: LIC4 implemented

- code/LIC_check.py
This function checks if there exists at least one set of two consecutive data points: 
(x[i],y[i]) and (x[j],y[j]), such that x[j] - x[i] < 0.
> feat LIC 5 implemented

- code/LIC_check.py
> Fix Issue/3

- code/LIC_check.py
The function verify if there exists at least one set of n_pts consecutive data points such that at least one of them lies at a distance greater than dist from the line joining the first and last of these points.
fix #8
> Feat LIC 6 check implemented

- code/LIC_check.py
- code/test_LIC_check.py
This PR includes the following changes:
Feature Implementation:
- Added the complete implementation of LIC 14.
Unit Tests:
- Created comprehensive unit tests using pytest to validate the correctness of LIC 14.
- Tests cover both standard cases and edge cases to ensure reliability.
Linked Issue:
Closes #16
> Implement LIC 14 with Unit Tests (Closes #16)

- code/LIC_check.py
- code/test_LIC_check.py
Deleted some code in the merge, restored it to the right version
> Fix merge of feat LIC 10 (issue #12) and main

- code/LIC_check.py
Refactor LIC 10 (issue #12) according to the changes made in LIC 14 (issue #16).
Reuse of the triangle math code.
Add formula used.
> refactor LIC 10 according to the changes made in LIC 14

- code/LIC_check.py
- code/test_LIC_check.py
> Feat LIC 11 check implemented (complete issue #13), add unit tests for LIC 11

- code/LIC_check.py
- code/test_LIC_check.py
Refactor LIC unit tests to be under a common class.
Tests implemented for LICs in issues #2, #4, #5, #12, #13, #16
> Refactor LIC unit tests to be under a common class.

- code/LIC_check.py
- code/test_LIC_check.py
> Feat LIC 12 check implemented (complete issue #14), add unit tests for LIC 10

- code/LIC_check.py
- code/test_LIC_check.py
Refactor calculate distance, and add appropriate tests.
Used by LICs related to #2, #3, #8, #9, #14
> Refactor calculate_distance, add tests

- code/LIC_check.py
> Fix issue/11

- code/LIC_check.py
LIC 13 implemented
calculate_circumcenter function implemented for LIC 1 and LIC 13
> fix issue 15

- code/LIC_check.py
Initial implementation of LIC 13 was wrong, now fixed.
> fix Issue/15

- code/LIC_check.py
Condition b for LIC 13 now implemented correctly.
> fix: minor changes to LIC 13 implementation

- code/LIC_check.py
- code/test_LIC_check.py
Unittests calculate_circumcenter, LIC 7, 9, 13 implemented
Added conditions for input LIC 7, 9, 13 functions
> feat: Unittests LIC 7, 9, 13

- README.md
Updated README implementing:
- description
- project structure, whitch include all the files inside the different folders
- installation of the software
- how to run the program
- how the code works
- contributors and member of the group
- license
> Doc: updated README

- README.md
- Implemented the workload in the contributors part, it shows how we have split the work
- Implemented a new section dedicated to how Run the test for the software
- Modified the line dedicated to the install of the dependencies
> doc: implemented new parts in the README

- README.md
- Way-of-Working.md
> Doc add Way-of-Working (issue #69)

- README.md
- Way-of-Working.md
Add instructions/versions for:
> Doc/fix readme (add python and pip versions, #issue #68)

- README.md
Add contributions for last changes related to issue #68
> Doc add contributions for last changes (issue #68)
